version: '2'
services:
    webserver:
      image: nginx
      restart: always
      ports:
        - "${NGINX_PUBLIC_PORT}:80"
      volumes:
        - "./nginx/nginx-not-secure.conf:/etc/nginx/nginx.conf"
      networks:
        - gogs
    postgres:
      image: postgres:9.5
      restart: always
      environment:
        - "POSTGRES_USER=${POSTGRES_USER}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=gogs"
      volumes:
        - "db-data:/var/lib/postgresql/data"
      networks:
        - gogs
    gogs:
      image: gogs/gogs:latest
      restart: always
      ports:
        - "${SSH_PUBLIC_PORT}:22"
      expose:
         - "3000"
      links:
        - postgres
      environment:
        - "RUN_CROND=true"
      networks:
        - gogs
      volumes:
        - "gogs-data:/data"
      depends_on:
        - postgres
        - webserver

networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local

