version: '2'
services:
    postgres:
      image: postgres:9.5
      restart: always
      environment:
        - "POSTGRES_USER=${POSTGRES_USER}"
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=gogs"
      volumes:
        - "db-data:/var/lib/postgresql/data"
      networks:
        - gogs
    gogs:
      image: gogs/gogs:latest
      restart: always
      ports:
        - "127.0.0.1:${SSH_PUBLIC_PORT}:22"
        - "127.0.0.1:${WEB_PUBLIC_PORT}:3000"
      links:
        - postgres
      networks:
        - gogs
      volumes:
        - "gogs-data:/data"
      depends_on:
        - postgres

networks:
    gogs:
      driver: bridge

volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local

